// GENERATED by scripts/gen_desktop_contracts.py from src/sletchy/cli/bridge_contracts.py.
// Do not edit. The schema is typed once, in Python (LAW 6), and
// tests/unit/test_desktop_contracts.py fails when this file is stale.

/// The only methods the window may ask the bridge for. The bridge enforces the
/// same list independently; this copy refuses a request before it crosses a pipe.
pub const METHODS: &[&str] = &[
    "status",
    "selfcheck",
    "flags.list",
    "flags.set",
    "ledger.tail",
    "ledger.payload",
    "stop.plan",
    "stop.run",
    "models.list",
    "model.ask",
    "model.load",
    "model.unload",
    "model.answer",
    "init",
];

/// The bridge protocol this shell speaks. A mismatch is refused at startup.
pub const PROTOCOL_VERSION: u32 = 2;
