"""Generate the desktop shell's types from the bridge's Pydantic models (LAW 6).

Writes two files, both marked GENERATED and both checked by
`tests/unit/test_desktop_contracts.py`, which fails when either is stale:

- `apps/desktop/src/generated/contracts.ts` - every params and result type, the
  method table, and the error codes, for the window
- `apps/desktop/src-tauri/src/methods.rs` - the method allowlist the Rust shell
  enforces before a request ever reaches the bridge

Run after changing `src/sletchy/cli/bridge_contracts.py`:

    uv run python scripts/gen_desktop_contracts.py

Deliberately a small converter for the JSON Schema subset Pydantic emits for these
models, not a general one. An unsupported construct raises rather than guessing.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

from sletchy.cli.bridge_contracts import ERROR_CODES, METHODS, PROTOCOL_VERSION

ROOT = Path(__file__).resolve().parents[1]
TS_OUT = ROOT / "apps" / "desktop" / "src" / "generated" / "contracts.ts"
RS_OUT = ROOT / "apps" / "desktop" / "src-tauri" / "src" / "methods.rs"

HEADER = (
    "GENERATED by scripts/gen_desktop_contracts.py from src/sletchy/cli/bridge_contracts.py.\n"
    "Do not edit. The schema is typed once, in Python (LAW 6), and\n"
    "tests/unit/test_desktop_contracts.py fails when this file is stale."
)

Schema = dict[str, Any]


class Unsupported(ValueError):
    pass


def ts_type(schema: Schema, defs: dict[str, Schema], emit: dict[str, Schema]) -> str:
    if "$ref" in schema:
        name = schema["$ref"].rsplit("/", 1)[-1]
        emit.setdefault(name, defs[name])
        return name
    if "anyOf" in schema:
        return " | ".join(ts_type(s, defs, emit) for s in schema["anyOf"])
    if "const" in schema:
        return json.dumps(schema["const"])
    if "enum" in schema:
        return " | ".join(json.dumps(v) for v in schema["enum"])
    kind = schema.get("type")
    if kind == "string":
        return "string"
    if kind in ("integer", "number"):
        return "number"
    if kind == "boolean":
        return "boolean"
    if kind == "null":
        return "null"
    if kind == "array" and "items" in schema:
        return f"readonly {wrap(ts_type(schema['items'], defs, emit))}[]"
    if kind == "object" and "properties" not in schema:
        return "Record<string, unknown>"
    raise Unsupported(f"no TypeScript mapping for {schema}")


def wrap(t: str) -> str:
    return f"({t})" if " | " in t else t


def interface(name: str, schema: Schema, defs: dict[str, Schema], emit: dict[str, Schema]) -> str:
    props: dict[str, Schema] = schema.get("properties", {})
    required = set(schema.get("required", []))
    doc = schema.get("description", "").strip()
    lines = [f"/** {doc.splitlines()[0]} */"] if doc else []
    if not props:
        lines.append(f"export type {name} = Record<string, never>;")
        return "\n".join(lines)
    lines.append(f"export interface {name} {{")
    for key, prop in props.items():
        optional = "" if key in required else "?"
        lines.append(f"  readonly {key}{optional}: {ts_type(prop, defs, emit)};")
    lines.append("}")
    return "\n".join(lines)


def render_ts() -> str:
    emit: dict[str, Schema] = {}
    defs: dict[str, Schema] = {}
    rows: list[str] = []
    for method, (params, result) in METHODS.items():
        for model, mode in ((params, "validation"), (result, "serialization")):
            schema = model.model_json_schema(mode=mode)  # type: ignore[arg-type]
            defs.update(schema.pop("$defs", {}))
            emit.setdefault(model.__name__, schema)
        rows.append(f'  "{method}": {{ params: {params.__name__}; result: {result.__name__} }};')

    blocks: list[str] = []
    done: set[str] = set()
    while len(done) < len(emit):  # emitting can discover nested $defs
        for name in sorted(set(emit) - done):
            blocks.append(interface(name, emit[name], defs, emit))
            done.add(name)

    codes = ", ".join(json.dumps(c) for c in ERROR_CODES)
    names = ", ".join(json.dumps(m) for m in METHODS)
    head = "\n".join(f"// {line}" for line in HEADER.splitlines())
    return (
        f"{head}\n\n"
        f"export const PROTOCOL_VERSION = {PROTOCOL_VERSION};\n\n"
        f"export const ERROR_CODES = [{codes}] as const;\n"
        "export type ErrorCode = (typeof ERROR_CODES)[number];\n\n"
        f"export const METHOD_NAMES = [{names}] as const;\n\n"
        + "\n\n".join(blocks)
        + "\n\n/** Every method the bridge answers, with its params and result. */\n"
        "export interface Methods {\n" + "\n".join(rows) + "\n}\n\n"
        "export type MethodName = keyof Methods;\n"
    )


def render_rs() -> str:
    head = "\n".join(f"// {line}" for line in HEADER.splitlines())
    names = "\n".join(f'    "{m}",' for m in METHODS)
    return (
        f"{head}\n\n"
        "/// The only methods the window may ask the bridge for. The bridge enforces the\n"
        "/// same list independently; this copy refuses a request before it crosses a pipe.\n"
        f"pub const METHODS: &[&str] = &[\n{names}\n];\n\n"
        "/// The bridge protocol this shell speaks. A mismatch is refused at startup.\n"
        f"pub const PROTOCOL_VERSION: u32 = {PROTOCOL_VERSION};\n"
    )


def main() -> int:
    check = "--check" in sys.argv
    stale = []
    for path, text in ((TS_OUT, render_ts()), (RS_OUT, render_rs())):
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == text:
            continue
        if check:
            stale.append(str(path.relative_to(ROOT)))
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8", newline="\n")
        print(f"wrote {path.relative_to(ROOT)}")
    if stale:
        print("stale, re-run scripts/gen_desktop_contracts.py:\n  " + "\n  ".join(stale))
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
